Database:
  Mysql: true
  Host: "35.239.132.204"
  Port: 3306
  Username: "Neonzio"
  Password: "redmysqlsenha1234"
  Database: "redplugins"
  Table: "redcashtest"
  
debugUUID: true
backupState: true
versionChecker: true