name: RedCash
description: RedCash
main: me.neon.redcash.RedCash
version: 0.9
author: redplugins
softdepend: [PlaceHolderAPI]
commands:
  cash:
    description: Reloads the configuration file
    default: true
    usage: /cash reload
  permissions:
  cash.*:
    description: Inherits all plugin permissions
