#Settings for a connection to your database
Database:
  #To use Mysql set to 'true', if you don't want to use it, set to 'false'.
  Use: true
  Host: "104.197.88.160"
  Port: 3306
  Username: "Neonzio"
  Password: "redpluginsadmin86910"
  Database: "redplugins"
  Table: "redcash"
 
#Send an alert to all players when an automatic backup is performed 
backupAlertForPlayers: true 
#Automatic backup enabled or disabled
backupState: true